apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: d-file-lrs
  name: my-azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: my-azurefile
  resources:
    requests:
      storage: 1Gi